# Generated by Django 2.2.1 on 2019-06-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='amenities',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='bath',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='rent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
