# Generated by Django 2.2.1 on 2019-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20190614_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='rent',
            new_name='price',
        ),
        migrations.AddField(
            model_name='group',
            name='photos',
            field=models.FileField(default='http://clipart-library.com/images/pc78gb4Li.png', upload_to='housepics'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
