# Generated by Django 2.2.1 on 2019-07-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20190614_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='photos',
        ),
    ]
