# Generated by Django 2.2.1 on 2019-07-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove_group_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['address']},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='address',
        ),
    ]
